### ISSUE TITLE
Not sure how this module has to be configured

### ISSUE THREAD

**Issue by andoro** [Toutouwai/WebpToJpg#2]
Dear Robin S,

I tried this module yesterday during migrating one of my project to ProcessWire.
However it seems it doesn't works for me.
I added an image field and set webp as a format, so I could upload a webp file, but I don't see where the JPG format generated.
We would like to this module as well to store images on Cloudflare: https://processwire.com/talk/topic/28412-cloudflareassets/
I'm not sure if this is compatible with you module.

**Comment by Toutouwai** [comment]
Maybe your server environment doesn't have the necessary PHP extensions to convert from WebP. I just released v0.2.1 which will show an error message if the environment is inadequate. Please update to v0.2.1 and try again to upload a WebP image to your field, then save the page. If you see the error message then that's your problem. If not then please share a screen recording or screenshots of the issue because your report doesn't have a lot of detail.

I don't know about the CloudflareAssets module. When you resolve the current issue I guess try it and find out.

**Comment by andoro** [comment]
Thank you, I updated to this latest version, also removed the Cloudflareassets module and now your module works like a charm.  😀 
Sorry I don't have too much time to debug, but I suppose that these 2 modules are not yet compatible. I had to delete CF module, because neither image edits nor page duplicates (containing related images) are saved to CF R2 so for me this modules is not usable.

**Comment by Toutouwai** [comment]
Glad to hear you could get it working.
